[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "conditional-tokens-market-makers=lib/conditional_tokens_market_makers",
  "conditional-tokens=lib/conditional_tokens_contracts"
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[dependencies]
conditional_tokens_market_makers = { git = "https://github.com/gnosis/conditional-tokens-market-makers.git", tag = "v1.8.1" }
conditional_tokens_contracts = { git = "https://github.com/gnosis/conditional-tokens-contracts.git", tag = "v1.0.3" }
