[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.5.17"  # Solidity 0.5 系の最新安定版
rpc_url = "https://base-sepolia.g.alchemy.com/v2/k3Dvibh6qSOCk1KkssKyZub9r6AuK1qy"
remappings = [
    "openzeppelin-solidity=lib/openzeppelin-solidity",
    "conditional-tokens-market-makers=lib/conditional-tokens-market-makers",
    "conditional-tokens/contracts=lib/conditional-tokens-contracts/contracts",
    "forge-std=lib/forge-std/src",
    "@gnosis.pm/conditional-tokens-contracts=lib/conditional-tokens-contracts"
]

[rpc_endpoints]
local = "http://localhost:8548"